// setup-env.js (Final Version)

const fs = require('fs');
const prodConfigContent = `
// This file is generated by setup-env.js during the production build.
// DO NOT MODIFY MANUALLY.
export const firebaseConfig = { // <-- Use the final name: firebaseConfig
    apiKey: "${process.env.FIREBASE_API_KEY}",
    authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
    databaseURL: "${process.env.FIREBASE_DATABASE_URL}",
    projectId: "${process.env.FIREBASE_PROJECT_ID}",
    storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${process.env.FIREBASE_APP_ID}",
};
`;

const targetPath = 'src/app/config/firebase-prod.config.ts';
fs.writeFileSync(targetPath, prodConfigContent);
